apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - caddy-gateway.yaml
  - auth.yaml
  - portal.yaml
  - landing.yaml
  - dev-dashboard.yaml
  - dev-hub.yaml
  - app-expenses.yaml
  - app-billing.yaml
  - app-telemetry.yaml
