#!/usr/bin/env bun
/**
 * @forge/scripts/log-security-audit - Centralized Security Audit Logger
 * Google & Meta Clean Architecture Standard (2026 LTS Baseline)
 *
 * Persists Strix security audit reports to logs/security/:
 * 1. Appends structured machine-readable JSONL entry to logs/security/audit.jsonl.
 * 2. Writes full Markdown audit report to logs/security/YYYY-MM/AUDIT_YYYYMMDD_HHmm_<mode>.md.
 * 3. Updates logs/security/LATEST_AUDIT.md pointer.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';

const REPO_ROOT = process.cwd();
const SECURITY_LOGS_DIR = join(REPO_ROOT, 'logs', 'security');
const AUDIT_JSONL_PATH = join(SECURITY_LOGS_DIR, 'audit.jsonl');
const LATEST_AUDIT_PATH = join(SECURITY_LOGS_DIR, 'LATEST_AUDIT.md');

export interface SecurityAuditRecord {
  timestamp: string;
  mode: 'code-check' | 'live-test' | 'pre-commit';
  target: string;
  status: 'PASSED' | 'WARNING' | 'FAILED';
  findingsCount: number;
  summary: string;
  reportFile: string;
}

export interface LogAuditOptions {
  mode: 'code-check' | 'live-test' | 'pre-commit';
  target: string;
  status: 'PASSED' | 'WARNING' | 'FAILED';
  findingsCount?: number;
  summary?: string;
  markdownContent?: string;
}

/**
 * Persists a security audit record and markdown report to logs/security/.
 */
export function recordSecurityAudit(options: LogAuditOptions): SecurityAuditRecord {
  const now = new Date();
  const timestamp = now.toISOString();
  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, '0');
  const day = String(now.getUTCDate()).padStart(2, '0');
  const hours = String(now.getUTCHours()).padStart(2, '0');
  const minutes = String(now.getUTCMinutes()).padStart(2, '0');

  const monthDirName = `${year}-${month}`;
  const targetMonthDir = join(SECURITY_LOGS_DIR, monthDirName);

  if (!existsSync(targetMonthDir)) {
    mkdirSync(targetMonthDir, { recursive: true });
  }

  const safeMode = options.mode.toLowerCase().replace(/[^a-z0-9_-]/g, '');
  const reportFileName = `AUDIT_${year}${month}${day}_${hours}${minutes}_${safeMode}.md`;
  const reportFilePath = join(targetMonthDir, reportFileName);
  const relReportPath = `logs/security/${monthDirName}/${reportFileName}`;

  const findingsCount = options.findingsCount ?? 0;
  const summary = options.summary ?? `Strix ${options.mode} completed with status ${options.status}`;

  const defaultMarkdown = `# 🛡️ Strix Security Audit Report: ${options.mode.toUpperCase()}

- **Timestamp**: ${timestamp}
- **Target**: \`${options.target}\`
- **Execution Mode**: ${options.mode}
- **Status**: \`${options.status}\`
- **Findings Count**: ${findingsCount}
- **Summary**: ${summary}

---

## Findings Summary
${findingsCount === 0 ? '✅ **Zero security vulnerabilities detected.** All inspected invariants passed.' : `⚠️ **${findingsCount} finding(s) detected.** See details below.`}

---

*Generated by Strix Security Auditor. Logged to [audit.jsonl](file:///home/sanket/Desktop/Sanket/org_website_clone/logs/security/audit.jsonl).*
`;

  const reportBody = options.markdownContent && options.markdownContent.trim().length > 0
    ? options.markdownContent.trim()
    : defaultMarkdown;

  // 1. Write monthly report file
  writeFileSync(reportFilePath, `${reportBody}\n`, 'utf8');

  // 2. Update LATEST_AUDIT.md
  writeFileSync(LATEST_AUDIT_PATH, `${reportBody}\n`, 'utf8');

  // 3. Append to audit.jsonl
  const record: SecurityAuditRecord = {
    timestamp,
    mode: options.mode,
    target: options.target,
    status: options.status,
    findingsCount,
    summary,
    reportFile: relReportPath,
  };

  appendFileSync(AUDIT_JSONL_PATH, `${JSON.stringify(record)}\n`, 'utf8');

  return record;
}

// CLI entrypoint
if (import.meta.main) {
  const args = process.argv.slice(2);
  let mode: 'code-check' | 'live-test' | 'pre-commit' = 'code-check';
  let target = 'repo';
  let status: 'PASSED' | 'WARNING' | 'FAILED' = 'PASSED';
  let findingsCount = 0;
  let summary = 'Security audit completed';
  let markdownContent = '';

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--mode' && args[i + 1]) {
      mode = args[++i] as 'code-check' | 'live-test' | 'pre-commit';
    } else if (arg === '--target' && args[i + 1]) {
      target = args[++i];
    } else if (arg === '--status' && args[i + 1]) {
      status = args[++i] as 'PASSED' | 'WARNING' | 'FAILED';
    } else if (arg === '--findings-count' && args[i + 1]) {
      findingsCount = parseInt(args[++i], 10) || 0;
    } else if (arg === '--summary' && args[i + 1]) {
      summary = args[++i];
    } else if (arg === '--markdown' && args[i + 1]) {
      const val = args[++i];
      if (existsSync(val)) {
        markdownContent = readFileSync(val, 'utf8');
      } else {
        markdownContent = val;
      }
    }
  }

  const record = recordSecurityAudit({
    mode,
    target,
    status,
    findingsCount,
    summary,
    markdownContent,
  });

  console.log(`🛡️ [Strix Security Logger] Audit recorded successfully:`);
  console.log(`   └─ Status: ${record.status}`);
  console.log(`   └─ Mode: ${record.mode}`);
  console.log(`   └─ Target: ${record.target}`);
  console.log(`   └─ Report: ${record.reportFile}`);
}
